kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: vol-omd-postgres
  namespace: omd
spec:
  selector:
    matchLabels:
      type: postgres
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi