kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: openmetadata-dependencies-logs
  namespace: omd
  labels:
    app: airflow
spec:
  selector:
    matchLabels:
      type: logs
  accessModes:
    - ReadWriteMany
  storageClassName: local-storage
  resources:
    requests:
      storage: 3Gi